### ISSUE TITLE
Idea: make it easier to create links that open in new windows

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk-components#360]
[According to the design system,](https://design-system.service.gov.uk/styles/typography/#opening-links-in-a-new-tab) links that open in new tabs/windows need to:

* have `target: "_blank"`
* be `rel: "noreferrer noopener"` (to prevent [reverse tabnabbing](https://owasp.org/www-community/attacks/Reverse_Tabnabbing))
* include a description that informs the user the window will open in a new window, usually `(opens in new tab)` or similar

Rather than having to remember all of these things every time, we could bake the functionality into the library. It could be implemented as:

* a new helper - perhaps `#govuk_external_link_to`
* via a keyword argument on `#govuk_link_to` and friends - maybe `external: true`

The text appended to the end should be `nil` by default (leaving it to the dev) but can be defaulted so it always adds the `(link opens in new tab)` suffix - unless supressed with `external_text: nil` or similar.

**Comment by cpjmcquillan** [comment]
Yeah, this is probably worthwhile.

Teaching Vacancies [defined a custom helper](https://github.com/DFE-Digital/teaching-vacancies/blob/f61a19827982abadcad42f4de8371db30b04ee8d/app/helpers/links_helper.rb#L33-L35) for this a while back.

I'd imagine other teams have defined similar helpers too, so I think there is value in extracting something out into this gem.

**Comment by peteryates** [comment]
That looks perfect, thanks @cpjmcquillan!

Definitely feels like a separate method is the way to go, rather than adding more args to `#govuk_link_to`.

<kbd>CTRL + c</kbd> → <kbd>CTRL + v</kbd>

**Comment by frankieroberto** [comment]
I like this idea, but I think we should avoid using the word `external` in the helper method name or attributes, as the Design System doesn’t say to open external links in a new tab - most of the time they shouldn't be.

I think the most developer-friendly thing to do would be an additional keyword argument on the existing helper. So perhaps something like this:

```ruby
<%= govuk_link_to "privacy policy", privacy_policy_path, new_tab: true %>
```

We could also allow a string to be set instead of a boolean, for cases where you might want to rewrite the additional text shown (eg if translating into another language):

```ruby
<%= govuk_link_to "privacy policy", privacy_policy_path, new_tab: "(opens in new tab)" %>
```

(An empty string could be set if you really don’t want to include any additional text)

**Comment by peteryates** [comment]
Sounds like a sensible approach @frankieroberto - `new_tab` feels like the way to go.

* `false` by default
* when `true` it pulls the text from a config setting which defaults to `(opens in new tab)` - depends on (#355)
* when a string it overrides the default text
