### ISSUE TITLE
Link/mail helpers overwriting classes

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/govuk-components#74]
I've noticed that when supplying custom classes to these helpers, the `govuk-link` class is no longer applied (i.e overwritten rather than merged).

Adding this issue so 
a) I don't forget about it
b) Someone else can investigate/fix if they feel inclined to do so

**Comment by peteryates** [comment]
I was hoping that [this](https://github.com/DFE-Digital/govuk-components/blob/master/app/helpers/govuk_link_helper.rb#L3) could be done in a clean elegant fashion using some combination of `deep_merge` but it's a faff because classes can be passed in as either a string or array. I think just manually ensuring that the class contains `govuk-link` via `<<` is the way to go here, even though it's a bit ugly.
